$schema: http://json-schema.org/draft-07/schema#
allOf:
- $ref: ../../base_concrete_step.yaml
- properties:
    type:
      const: common:noop
    config:
      type: object
      required:
      - reason
      properties:
        reason:
          type: string
          description: "why this step was skipped"

